const ROUTES = {
  HOME: '/',
  HISTORY: '/history',
  LOGIN: '/login',
  DEVICE: '/device',
  DEVICE_MANAGEMENT: '/device-management',
  DEVICE_PROFILE: '/device-profile',
  LOCATION: '/location',
  REPORT: '/report',
  FIRE_ALERTS: '/fire-alerts',
  HUMAN_RESOURCES: '/human-resources',
  CUSTOMER_MANAGEMENT: '/customer-management',
  TENANT: '/tenant/:tenantCode',
  VIEW_DEVICE_BY_DEVICEPROFILE_ID: '/device-profile/:deviceProfileId/device',
  SETTING: '/setting',
  TOOLS: '/tools',
  DASHBOARD: '/dashboard/:dashboardId',
  CONFIGURATION: '/configuration',
	ENERGY: '/energy',
	STREET_LIGHT: '/street-light',
	CCTV: '/cctv',
	TRAFFIC_LIGHT: '/traffic-light',
	FIRE_ALARM: '/fire-alarm',
};

export default ROUTES;
