export enum USER_ROLE {
  TENANT = 'TENANT',
  SYSADMIN = 'SYSADMIN',
  STAFF = 'STAFF'
}

export enum MODE_RESET_PASSWORD_FORM {
  RESET_PASSWORD_FORM = 'RESET_PASSWORD_FORM',
  OTP_PASSWORD_FORM = 'OTP_PASSWORD_FORM',
  NEW_PASSWORD_FORM = 'NEW_PASSWORD_FORM'
}

export enum INDEX_SETTING {
  UPDATE_INFO_ACCOUNT = 'UPDATE_INFO_ACCOUNT',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  LANGUAGE = 'LANGUAGE'
}

export enum LANG_OPTIONS {
  LANG_ENG = 'en',
  LANG_VI = 'vi'
}
