export const DATA_STATUS = {
  SKIP: 'SKIP',
  VERIFY: 'VERIFY',
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  IS_WARNING: 'IS_WARNING',
  WARNING: 'WARNING',
  CLOSED: 'CLOSED',
  USED: 'USED',
  UNUSED: 'UNUSED',
  STOP_WARNING: 'STOP_WARNING',
  LOST_CONNECT: 'LOST_CONNECT',
  CONNECTED: 'CONNECTED',
  ALARM: 'ALARM',
  IGNORE: 'IGNORE',
  PENDING: 'PENDING',
  DISCONNECTED: 'DISCONNECTED',
  CONFIRM: 'CONFIRM'
};
