import { latLng } from 'leaflet';

export const cctvDevices = [
  {
    id: 'CAM-CK-001',
    location: 'Highland Rd & Elm St.',
    type: 'Fixed Mini Bullet Camera',
    power: '220V AC',
    status: 'Maintenance',
    statusColor: '#00e676',
    latLng: latLng(10.85561, 106.631128),
    updatedAt: '8 sec ago',
    resolution: '4K UHD (3840×2160)',
    lens: '2.8mm Fixed',
    nightVersion: 'ColorVu',
    irRange: '30m',
    smartFeatures: 'Human/vehicle detection',
    protection: 'IP67',
  },
  {
    id: 'CAM-CK-002',
    location: 'Highland Rd & Elm St.',
    type: 'Fixed Mini Bullet Camera',
    power: '220V AC',
    status: 'Error',
    statusColor: '#00e676',
    latLng: latLng(10.855641, 106.631699),
    updatedAt: '8 sec ago',
    resolution: '4K UHD (3840×2160)',
    lens: '2.8mm Fixed',
    nightVersion: 'ColorVu',
    irRange: '30m',
    smartFeatures: 'Human/vehicle detection',
    protection: 'IP67',
  },
  {
    id: 'CAM-CK-003',
    location: 'Highland Rd & Elm St.',
    type: 'Fixed Mini Bullet Camera',
    power: '220V AC',
    status: 'Active',
    statusColor: '#ff5252',
    latLng: latLng(10.85646, 106.630954),
    updatedAt: '12:18:22, 05-15-2025',
    resolution: '4K UHD (3840×2160)',
    lens: '2.8mm Fixed',
    nightVersion: 'ColorVu',
    irRange: '30m',
    smartFeatures: 'Human/vehicle detection',
    protection: 'IP67',
  },
  {
    id: 'CAM-CK-004',
    location: 'Highland Rd & Elm St.',
    type: 'Fixed Mini Bullet Camera',
    power: '220V AC',
    status: 'Offline',
    statusColor: '#b0b9c6',
    latLng: latLng(10.856525, 106.631692),
    updatedAt: '12:18:22, 05-15-2025',
    resolution: '4K UHD (3840×2160)',
    lens: '2.8mm Fixed',
    nightVersion: 'ColorVu',
    irRange: '30m',
    smartFeatures: 'Human/vehicle detection',
    protection: 'IP67',
  },
  {
    id: 'CAM-CK-005',
    location: 'Highland Rd & Elm St.',
    type: 'Fixed Mini Bullet Camera',
    power: '220V AC',
    status: 'Active',
    statusColor: '#ffd600',
    latLng: latLng(10.856494, 106.631313),
    updatedAt: '8 sec ago',
    resolution: '4K UHD (3840×2160)',
    lens: '2.8mm Fixed',
    nightVersion: 'ColorVu',
    irRange: '30m',
    smartFeatures: 'Human/vehicle detection',
    protection: 'IP67',
  },
  {
    id: 'CAM-CK-006',
    location: 'Highland Rd & Elm St.',
    type: 'Fixed Mini Bullet Camera',
    power: 'PoE / 12V DC',
    status: 'Active',
    statusColor: '#00e676',
    latLng: latLng(10.856052, 106.631706),
    updatedAt: '8 sec ago',
    resolution: '4K UHD (3840×2160)',
    lens: '2.8mm Fixed',
    nightVersion: 'ColorVu',
    irRange: '30m',
    smartFeatures: 'Human/vehicle detection',
    protection: 'IP67',
  },
];

export const statusList = [
  { label: 'Active', value: 26.5, color: '#5FE9D0' },
  { label: 'Maintenance', value: 23.14, color: '#FAC515' },
  { label: 'Error', value: 20.5, color: '#F97066' },
  { label: 'Offline', value: 10.28, color: '#D0D5DD' },
];

export const statusColorMap: Record<string, string> = {
  Active: '#00e676',
  Error: '#ff5252',
  Offline: '#b0b9c6',
  Maintenance: '#ffd600',
};

export const cctvPolygonCoords = cctvDevices.map(cctv => [cctv.latLng.lat, cctv.latLng.lng]);
